plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.jmix'
version = '0.0.1-SNAPSHOT'
description = 'mcp-docs'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
//    maven { url 'https://repo.spring.io/milestone' }
//    maven { url 'https://repo.spring.io/snapshot' }
}

ext {
    set('springAiVersion', "1.1.0-M1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Spring AI - Embedding Models
    implementation "org.springframework.ai:spring-ai-openai:${springAiVersion}"
    implementation "org.springframework.ai:spring-ai-starter-model-anthropic"

    implementation 'org.commonmark:commonmark:0.24.0'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.asciidoctor:asciidoctorj:3.0.0'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'

    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation 'com.google.guava:guava:33.5.0-jre'

    // MCP Server
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc'
    implementation "org.springframework.ai:spring-ai-pgvector-store"
    implementation "org.springframework.ai:spring-ai-advisors-vector-store"

    // remove when available as sub-dependency
    implementation 'org.apache.commons:commons-lang3:3.18.0'

    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
