spring.application.name=mcp-docs


## Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
logging.level.io.jmix=DEBUG

# Embedding Model Configuration
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.server=DEBUG

jmix.ai.backend.url=${JMIX_AI_BACKEND_URL:http://localhost:8081}

spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/message
spring.ai.mcp.server.type=SYNC