spring.application.name=mcp-docs


## Default Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/mcp_docs
spring.datasource.username=vector_user
spring.datasource.password=vector_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.platform=postgres

reranker.url=http://localhost:7999/rerank

## Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
logging.level.io.jmix=DEBUG

## Vector Store Configuration
vector.search.default-limit=10
vector.search.similarity-threshold=0.7
vector.search.embedding-dimension=1536
vector.index.lists=100
vector.index.probes=10

# Embedding Model Configuration

logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.server=DEBUG

app.embedding.model.type=claude
spring.ai.model.chat=none
spring.ai.model.embedding=none


spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/message
spring.ai.mcp.server.transport=WEBMVC
spring.ai.mcp.server.type=SYNC

# OpenAI Configuration
#app.embedding.openai.api-key=${OPENAI_API_KEY}
#app.embedding.openai.model=text-embedding-3-small
#app.embedding.openai.base-url=https://api.openai.com

# Claude Configuration
app.embedding.claude.api-key=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
app.embedding.claude.model=claude-haiku-4-5-20251001
app.embedding.claude.base-url=https://api.anthropic.com


docs.base-url=https://docs.jmix.io/jmix
docs.initial-page=intro.html
docs.limit=0


# Server
server.port=8080